import productImage from "../assets/product.png";
// Define more comprehensive data type for products
interface ProductData {
  id: number;
  title: string;
  image: string;
  link: string;
  price: string;
  salePrice?: string;
  rating: number;
  reviewCount: number;
  isOnSale: boolean;
  inStock: boolean;
  dateAdded: string;
  categories: string[]; // Add categories field
}

export const productData: ProductData[] = [
  {
    id: 101,
    title: "Kids Striped T-Shirt",
    image: productImage,
    link: "/product/101",
    price: "22.99 US$",
    rating: 4.5,
    reviewCount: 128,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-09-28",
    categories: ["All", "t-shirts"]
  },
  {
    id: 102,
    title: "Baby Denim Overalls",
    image: productImage,
    link: "/product/102",
    price: "34.99 US$",
    salePrice: "27.99 US$",
    rating: 5,
    reviewCount: 93,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-09-28",
    categories: ["All", "BABY", "Best-Sellers"]
  },
  {
    id: 103,
    title: "Toddler Summer Hat",
    image: productImage,
    link: "/product/103",
    price: "14.50 US$",
    rating: 4,
    reviewCount: 42,
    isOnSale: false,
    inStock: false,
    dateAdded: "2023-03-15",
    categories: ["All", "BABY"]
  },
  {
    id: 104,
    title: "Kids Winter Jacket",
    image: productImage,
    link: "/product/104",
    price: "49.99 US$",
    salePrice: "39.99 US$",
    rating: 4.8,
    reviewCount: 214,
    isOnSale: true,
    inStock: true,
    dateAdded: "2022-10-05",
    categories: ["All", "Jackets", "Best-Sellers"]
  },
  {
    id: 105,
    title: "Children's Jogger Pants",
    image: productImage,
    link: "/product/105",
    price: "19.99 US$",
    rating: 3.5,
    reviewCount: 67,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-11-18",
    categories: ["All", "Joggers"]
  },
  {
    id: 106,
    title: "Infant Knit Sweater",
    image: productImage,
    link: "/product/106",
    price: "24.99 US$",
    rating: 4.2,
    reviewCount: 86,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-09-22",
    categories: ["All", "BABY", "Sweatshirts"]
  },
  {
    id: 107,
    title: "Kids Swim Shorts",
    image: productImage,
    link: "/product/107",
    price: "18.99 US$",
    salePrice: "14.99 US$",
    rating: 4.7,
    reviewCount: 112,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-05-12",
    categories: ["All", "SWIM", "Shorts", "SALE"]
  },
  {
    id: 108,
    title: "Baby Sleep Set",
    image: productImage,
    link: "/product/108",
    price: "29.99 US$",
    rating: 5,
    reviewCount: 176,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-07-30",
    categories: ["All", "BABY"]
  },
  {
    id: 109,
    title: "Kids Graphic Hoodie",
    image: productImage,
    link: "/product/109",
    price: "32.99 US$",
    rating: 4.6,
    reviewCount: 134,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-08-14",
    categories: ["All", "Hoodies"]
  },
  {
    id: 110,
    title: "Toddler Sneakers",
    image: productImage,
    link: "/product/110",
    price: "26.50 US$",
    salePrice: "19.99 US$",
    rating: 4.3,
    reviewCount: 89,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-02-27",
    categories: ["All", "Footwear", "SALE"]
  },
  {
    id: 111,
    title: "Baby Cotton Romper",
    image: productImage,
    link: "/product/111",
    price: "17.99 US$",
    rating: 4.9,
    reviewCount: 201,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-06-19",
    categories: ["All", "BABY", "Rompers"]
  },
  {
    id: 112,
    title: "Kids Raincoat",
    image: productImage,
    link: "/product/112",
    price: "39.99 US$",
    rating: 4.2,
    reviewCount: 77,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-09-08",
    categories: ["All", "Rainwear"]
  },
  {
    id: 113,
    title: "Toddler Beanie",
    image: productImage,
    link: "/product/113",
    price: "12.99 US$",
    rating: 4.1,
    reviewCount: 64,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-11-03",
    categories: ["All", "Accessories"]
  },
  {
    id: 114,
    title: "Kids Denim Jacket",
    image: productImage,
    link: "/product/114",
    price: "44.99 US$",
    salePrice: "34.99 US$",
    rating: 4.7,
    reviewCount: 152,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-08-21",
    categories: ["All", "Jackets", "SALE"]
  },
  {
    id: 115,
    title: "Baby Fleece Onesie",
    image: productImage,
    link: "/product/115",
    price: "23.50 US$",
    rating: 4.8,
    reviewCount: 108,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-10-17",
    categories: ["All", "BABY", "Onesies"]
  },
  {
    id: 116,
    title: "Toddler Leggings",
    image: productImage,
    link: "/product/116",
    price: "15.99 US$",
    rating: 4.3,
    reviewCount: 92,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-01-19",
    categories: ["All", "Leggings"]
  },
  {
    id: 117,
    title: "Kids Sports Jersey",
    image: productImage,
    link: "/product/117",
    price: "29.99 US$",
    salePrice: "24.99 US$",
    rating: 4.4,
    reviewCount: 87,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-04-22",
    categories: ["All", "Sportswear", "SALE"]
  },
  {
    id: 118,
    title: "Baby Sun Hat",
    image: productImage,
    link: "/product/118",
    price: "13.99 US$",
    rating: 4.6,
    reviewCount: 123,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-05-30",
    categories: ["All", "BABY", "Accessories"]
  },
  {
    id: 119,
    title: "Kids Cargo Shorts",
    image: productImage,
    link: "/product/119",
    price: "24.50 US$",
    rating: 4.2,
    reviewCount: 67,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-06-14",
    categories: ["All", "Shorts"]
  },
  {
    id: 120,
    title: "Toddler Sundress",
    image: productImage,
    link: "/product/120",
    price: "27.99 US$",
    salePrice: "21.99 US$",
    rating: 4.7,
    reviewCount: 139,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-04-08",
    categories: ["All", "Dresses", "SALE"]
  },
  {
    id: 121,
    title: "Baby Mittens",
    image: productImage,
    link: "/product/121",
    price: "9.99 US$",
    rating: 4.4,
    reviewCount: 72,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-12-05",
    categories: ["All", "BABY", "Accessories"]
  },
  {
    id: 122,
    title: "Kids Winter Boots",
    image: productImage,
    link: "/product/122",
    price: "42.99 US$",
    rating: 4.5,
    reviewCount: 103,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-10-29",
    categories: ["All", "Footwear"]
  },
  {
    id: 123,
    title: "Toddler Pajama Set",
    image: productImage,
    link: "/product/123",
    price: "19.99 US$",
    salePrice: "15.99 US$",
    rating: 4.8,
    reviewCount: 167,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-01-12",
    categories: ["All", "Sleepwear", "SALE"]
  },
  {
    id: 124,
    title: "Baby Socks Pack",
    image: productImage,
    link: "/product/124",
    price: "11.99 US$",
    rating: 4.3,
    reviewCount: 84,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-09-03",
    categories: ["All", "BABY", "Accessories"]
  },
  {
    id: 125,
    title: "Kids Backpack",
    image: productImage,
    link: "/product/125",
    price: "34.50 US$",
    rating: 4.6,
    reviewCount: 118,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-07-17",
    categories: ["All", "Accessories"]
  },
  {
    id: 126,
    title: "Toddler Rain Boots",
    image: productImage,
    link: "/product/126",
    price: "22.99 US$",
    salePrice: "18.99 US$",
    rating: 4.7,
    reviewCount: 97,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-03-28",
    categories: ["All", "Footwear", "SALE"]
  },
  {
    id: 127,
    title: "Baby Bib Set",
    image: productImage,
    link: "/product/127",
    price: "14.99 US$",
    rating: 4.4,
    reviewCount: 61,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-08-05",
    categories: ["All", "BABY", "Accessories"]
  },
  {
    id: 128,
    title: "Kids Swim Goggles",
    image: productImage,
    link: "/product/128",
    price: "12.50 US$",
    rating: 4.1,
    reviewCount: 48,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-06-02",
    categories: ["All", "SWIM", "Accessories"]
  },
  {
    id: 129,
    title: "Toddler Baseball Cap",
    image: productImage,
    link: "/product/129",
    price: "13.99 US$",
    rating: 4.3,
    reviewCount: 73,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-05-14",
    categories: ["All", "Accessories"]
  },
  {
    id: 130,
    title: "Baby Swaddle Blanket",
    image: productImage,
    link: "/product/130",
    price: "21.99 US$",
    salePrice: "17.99 US$",
    rating: 4.9,
    reviewCount: 183,
    isOnSale: true,
    inStock: true,
    dateAdded: "2022-11-27",
    categories: ["All", "BABY", "SALE"]
  },
  {
    id: 131,
    title: "Kids Slippers",
    image: productImage,
    link: "/product/131",
    price: "18.50 US$",
    rating: 4.6,
    reviewCount: 94,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-12-18",
    categories: ["All", "Footwear"]
  },
  {
    id: 132,
    title: "Toddler Denim Jeans",
    image: productImage,
    link: "/product/132",
    price: "24.99 US$",
    rating: 4.4,
    reviewCount: 106,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-02-09",
    categories: ["All", "Denim"]
  },
  {
    id: 133,
    title: "Baby Teething Toy",
    image: productImage,
    link: "/product/133",
    price: "9.99 US$",
    salePrice: "7.99 US$",
    rating: 4.7,
    reviewCount: 129,
    isOnSale: true,
    inStock: true,
    dateAdded: "2022-07-21",
    categories: ["All", "BABY", "SALE"]
  },
  {
    id: 134,
    title: "Kids Lunch Box",
    image: productImage,
    link: "/product/134",
    price: "16.99 US$",
    rating: 4.5,
    reviewCount: 88,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-08-13",
    categories: ["All", "Accessories"]
  },
  {
    id: 135,
    title: "Toddler Sweater",
    image: productImage,
    link: "/product/135",
    price: "27.99 US$",
    rating: 4.3,
    reviewCount: 76,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-10-11",
    categories: ["All", "Sweatshirts"]
  },
  {
    id: 136,
    title: "Baby Shoes",
    image: productImage,
    link: "/product/136",
    price: "19.99 US$",
    salePrice: "14.99 US$",
    rating: 4.6,
    reviewCount: 112,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-01-05",
    categories: ["All", "BABY", "Footwear", "SALE"]
  },
  {
    id: 137,
    title: "Kids Snowsuit",
    image: productImage,
    link: "/product/137",
    price: "59.99 US$",
    rating: 4.8,
    reviewCount: 143,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-11-08",
    categories: ["All", "Outerwear"]
  },
  {
    id: 138,
    title: "Toddler Hairband Set",
    image: productImage,
    link: "/product/138",
    price: "11.50 US$",
    rating: 4.2,
    reviewCount: 57,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-07-03",
    categories: ["All", "Accessories"]
  },
  {
    id: 139,
    title: "Baby Rattle",
    image: productImage,
    link: "/product/139",
    price: "8.99 US$",
    rating: 4.4,
    reviewCount: 83,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-06-22",
    categories: ["All", "BABY", "Toys"]
  },
  {
    id: 140,
    title: "Kids Bathrobe",
    image: productImage,
    link: "/product/140",
    price: "29.99 US$",
    salePrice: "23.99 US$",
    rating: 4.7,
    reviewCount: 108,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-03-03",
    categories: ["All", "Bath", "SALE"]
  },
  {
    id: 141,
    title: "Toddler Wool Coat",
    image: productImage,
    link: "/product/141",
    price: "44.99 US$",
    rating: 4.9,
    reviewCount: 156,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-09-17",
    categories: ["All", "Outerwear"]
  },
  {
    id: 142,
    title: "Baby Blanket",
    image: productImage,
    link: "/product/142",
    price: "24.50 US$",
    rating: 4.8,
    reviewCount: 172,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-08-27",
    categories: ["All", "BABY", "Bedding"]
  },
  {
    id: 143,
    title: "Kids Gloves",
    image: productImage,
    link: "/product/143",
    price: "15.99 US$",
    salePrice: "12.99 US$",
    rating: 4.3,
    reviewCount: 67,
    isOnSale: true,
    inStock: true,
    dateAdded: "2022-11-15",
    categories: ["All", "Accessories", "SALE"]
  },
  {
    id: 144,
    title: "Toddler Dress Shoes",
    image: productImage,
    link: "/product/144",
    price: "32.99 US$",
    rating: 4.6,
    reviewCount: 93,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-12-22",
    categories: ["All", "Footwear"]
  },
  {
    id: 145,
    title: "Baby Diaper Bag",
    image: productImage,
    link: "/product/145",
    price: "49.99 US$",
    rating: 4.7,
    reviewCount: 127,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-02-18",
    categories: ["All", "BABY", "Accessories"]
  },
  {
    id: 146,
    title: "Kids Sunglasses",
    image: productImage,
    link: "/product/146",
    price: "13.99 US$",
    salePrice: "10.99 US$",
    rating: 4.4,
    reviewCount: 81,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-05-28",
    categories: ["All", "Accessories", "SALE"]
  },
  {
    id: 147,
    title: "Toddler Mittens",
    image: productImage,
    link: "/product/147",
    price: "11.99 US$",
    rating: 4.2,
    reviewCount: 58,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-10-24",
    categories: ["All", "Accessories"]
  },
  {
    id: 148,
    title: "Baby Bottle Set",
    image: productImage,
    link: "/product/148",
    price: "18.50 US$",
    rating: 4.5,
    reviewCount: 104,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-07-09",
    categories: ["All", "BABY", "Feeding"]
  },
  {
    id: 149,
    title: "Kids Beach Towel",
    image: productImage,
    link: "/product/149",
    price: "19.99 US$",
    salePrice: "15.99 US$",
    rating: 4.3,
    reviewCount: 69,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-06-19",
    categories: ["All", "Bath", "SALE"]
  },
  {
    id: 150,
    title: "Toddler Swim Vest",
    image: productImage,
    link: "/product/150",
    price: "22.99 US$",
    rating: 4.8,
    reviewCount: 147,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-05-05",
    categories: ["All", "SWIM"]
  },
  {
    id: 151,
    title: "Baby High Chair",
    image: productImage,
    link: "/product/151",
    price: "79.99 US$",
    rating: 4.7,
    reviewCount: 119,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-09-11",
    categories: ["All", "BABY", "Furniture"]
  },
  {
    id: 152,
    title: "Kids Umbrella",
    image: productImage,
    link: "/product/152",
    price: "16.50 US$",
    salePrice: "13.50 US$",
    rating: 4.4,
    reviewCount: 89,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-04-14",
    categories: ["All", "Accessories", "SALE"]
  },
  {
    id: 153,
    title: "Toddler Scarf",
    image: productImage,
    link: "/product/153",
    price: "14.99 US$",
    rating: 4.3,
    reviewCount: 78,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-11-13",
    categories: ["All", "Accessories"]
  },
  {
    id: 154,
    title: "Baby Monitor",
    image: productImage,
    link: "/product/154",
    price: "69.99 US$",
    rating: 4.9,
    reviewCount: 213,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-08-19",
    categories: ["All", "BABY", "Electronics"]
  },
  {
    id: 155,
    title: "Kids Water Bottle",
    image: productImage,
    link: "/product/155",
    price: "17.99 US$",
    salePrice: "14.99 US$",
    rating: 4.6,
    reviewCount: 107,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-07-28",
    categories: ["All", "Accessories", "SALE"]
  },
  {
    id: 156,
    title: "Toddler Backpack",
    image: productImage,
    link: "/product/156",
    price: "23.50 US$",
    rating: 4.7,
    reviewCount: 132,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-08-03",
    categories: ["All", "Accessories"]
  },
  {
    id: 157,
    title: "Baby Crib Mobile",
    image: productImage,
    link: "/product/157",
    price: "29.99 US$",
    rating: 4.5,
    reviewCount: 96,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-07-15",
    categories: ["All", "BABY", "Toys"]
  },
  {
    id: 158,
    title: "Kids Watch",
    image: productImage,
    link: "/product/158",
    price: "21.99 US$",
    salePrice: "17.99 US$",
    rating: 4.3,
    reviewCount: 74,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-03-21",
    categories: ["All", "Accessories", "SALE"]
  },
  {
    id: 159,
    title: "Toddler Sunhat",
    image: productImage,
    link: "/product/159",
    price: "15.50 US$",
    rating: 4.4,
    reviewCount: 91,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-06-11",
    categories: ["All", "Accessories"]
  },
  {
    id: 160,
    title: "Baby Pacifier Set",
    image: productImage,
    link: "/product/160",
    price: "12.99 US$",
    rating: 4.2,
    reviewCount: 68,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-10-03",
    categories: ["All", "BABY", "Feeding"]
  },
  {
    id: 161,
    title: "Kids Rain Poncho",
    image: productImage,
    link: "/product/161",
    price: "18.99 US$",
    salePrice: "15.99 US$",
    rating: 4.3,
    reviewCount: 79,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-04-17",
    categories: ["All", "Rainwear", "SALE"]
  },
  {
    id: 162,
    title: "Toddler Sandals",
    image: productImage,
    link: "/product/162",
    price: "24.50 US$",
    rating: 4.6,
    reviewCount: 113,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-05-23",
    categories: ["All", "Footwear"]
  },
  {
    id: 163,
    title: "Baby Travel Crib",
    image: productImage,
    link: "/product/163",
    price: "89.99 US$",
    rating: 4.8,
    reviewCount: 145,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-09-29",
    categories: ["All", "BABY", "Furniture"]
  },
  {
    id: 164,
    title: "Kids School Bag",
    image: productImage,
    link: "/product/164",
    price: "35.99 US$",
    salePrice: "29.99 US$",
    rating: 4.7,
    reviewCount: 124,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-08-07",
    categories: ["All", "Accessories", "SALE"]
  },
  {
    id: 165,
    title: "Toddler Training Cup",
    image: productImage,
    link: "/product/165",
    price: "13.50 US$",
    rating: 4.4,
    reviewCount: 87,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-11-05",
    categories: ["All", "BABY", "Feeding"]
  },
  {
    id: 166,
    title: "Baby Bath Toys",
    image: productImage,
    link: "/product/166",
    price: "16.99 US$",
    rating: 4.2,
    reviewCount: 73,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-10-19",
    categories: ["All", "BABY", "Toys"]
  },
  {
    id: 167,
    title: "Kids Headphones",
    image: productImage,
    link: "/product/167",
    price: "24.99 US$",
    salePrice: "19.99 US$",
    rating: 4.5,
    reviewCount: 99,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-02-03",
    categories: ["All", "Electronics", "SALE"]
  },
  {
    id: 168,
    title: "Toddler Snow Boots",
    image: productImage,
    link: "/product/168",
    price: "37.99 US$",
    rating: 4.8,
    reviewCount: 137,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-11-29",
    categories: ["All", "Footwear"]
  },
  {
    id: 169,
    title: "Baby Bath Robe",
    image: productImage,
    link: "/product/169",
    price: "22.50 US$",
    rating: 4.6,
    reviewCount: 112,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-08-08",
    categories: ["All", "BABY", "Bath"]
  },
  {
    id: 170,
    title: "Kids Wall Decals",
    image: productImage,
    link: "/product/170",
    price: "19.99 US$",
    salePrice: "16.99 US$",
    rating: 4.4,
    reviewCount: 85,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-01-27",
    categories: ["All", "Decor", "SALE"]
  },
  {
    id: 171,
    title: "Toddler Storybooks",
    image: productImage,
    link: "/product/171",
    price: "14.99 US$",
    rating: 4.7,
    reviewCount: 128,
    isOnSale: false,
    inStock: true,
    dateAdded: "2023-07-10",
    categories: ["All", "Books"]
  },
  {
    id: 172,
    title: "Baby Night Light",
    image: productImage,
    link: "/product/172",
    price: "25.99 US$",
    rating: 4.9,
    reviewCount: 186,
    isOnSale: false,
    inStock: true,
    dateAdded: "2022-12-14",
    categories: ["All", "BABY", "Electronics"]
  },
  {
    id: 173,
    title: "Kids Desk Chair",
    image: productImage,
    link: "/product/173",
    price: "49.50 US$",
    salePrice: "39.99 US$",
    rating: 4.5,
    reviewCount: 103,
    isOnSale: true,
    inStock: true,
    dateAdded: "2023-09-01",
    categories: ["All", "SALE"]
  },
];

// Helper function to get all items in a category
export const getProductsByCategory = (category: string): ProductData[] => {
  if (category === "All") return productData;
  if (category === "SALE") return productData.filter(item => item.isOnSale);
  
  return productData.filter(item => 
    item.categories.includes(category)
  );
};
